### ISSUE TITLE
indicies of columns in data.y do not correspond to y1, y2, etc

### ISSUE THREAD

**Issue by the-moliver** [kwgoodman/numerox#17]
This is a potential source of confusion. One might expect something like this to work:
```
nidx = nx.tournament_int('charles') - 1
Y = data.region_isin(['train']).y[:, nidx]
```
It would be nice if there was syntax for indexing y with the tournament name. Something like:
```
Y = data.y['charles']
```
Going from
```
nidx = nx.tournament_int('charles')
```
to 
```
Y = data.y5
```
is currently pretty awkward.

**Comment by kwgoodman** [comment]
Try:
```y = data.y_for_tournament('charles')```

**Comment by the-moliver** [comment]
Ah somehow missed that. I knew there had to be a better way. Thanks
