### ISSUE TITLE
Should this incorporate NumerAPI?

### ISSUE THREAD

**Issue by philipcmonk** [kwgoodman/numerox#2]
The old API client was developed here:  https://github.com/numerai/numerapi

Should the API client for the new API be developed in a separate repo from this one, or should it be just one simple package?  I could see it going either way.

**Comment by kwgoodman** [comment]
My preference is to pull pieces of the numerai api into numerox as they are needed. So for the first release I'd like to be able to download the dataset and upload a submission.

As soon as the first release is out I'd like to move on to, well, depends on what there are tokens for at that time. Staking would be nice or leaderboard info.

I think once we can easily get tokens from the front end and start using the api we will get a better feel. 

Once things are looking stable in numerox we can dedicate a release for api stuff only.

**Comment by danlupei** [comment]
I'd argue for keeping the API itself in a separate package (numerapi) and make numerox rely on that. This way if somebody wants to write code relying on the API, they won't have to pull the entire numerox library.
Unless this is a large overhead for some reason - then it is better to leave it as one simple package.

**Comment by kwgoodman** [comment]
That make a lot of sense. Numerox can always wrap the functions from a numerapi package in a way that fits into numerox.

**Comment by kwgoodman** [comment]
But it only makes sense if the separate numerapi package was under active development

**Comment by danlupei** [comment]
Initially, numerapi needs just as much development such that it provides necessary functionality for numerox. Later on if somebody needs more, at least they will have a baseline to extend. Except for API changes there is not much maintenance to do over numerapi.

**Comment by kwgoodman** [comment]
@philipcmonk I agree with @danlupei. I think a separate package for the api stuff makes sense (broader user base than numerox and should be developed rapidly). I'm leaning towards pulling it out of the 0.0.1 release. I don't really know how to support it (user questions when something goes wrong, the only way I have to test it right now is manually, etc). Someone could start a package with what is in numerox if that helps. Since I will be a user my hope is that you will build the first version!

**Comment by philipcmonk** [comment]
I agree.  They're separate concerns, and it's easy to imagine another user for the API client.  It would also function as a clean, un-opinionated example for API clients in other languages.

If someone creates a reasonably complete client for the new API, it could potentially qualify for the first item in this list: https://github.com/numerai/submission-criteria/wiki/Bounty-Guidelines

**Comment by kwgoodman** [comment]
closed by https://github.com/kwgoodman/numerox/commit/120ac6624a5947c5ffe7b897f8f8c1d256a58cbe
