### ISSUE TITLE
nx.download throws Runtime error

### ISSUE THREAD

**Issue by qu0b** [kwgoodman/numerox#20]
# System: 
NumPy version 1.15.4
NumPy relaxed strides checking option: True
NumPy is installed in /usr/local/lib/python2.7/site-packages/numpy
Python version 2.7.15 (default, Aug 22 2018, 16:36:18) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
nose version 1.3.7

# Error

line: data = nx.download('numerai_dataset.zip')

Exception RuntimeError: RuntimeError('cannot join current thread',) in <bound method tqdm.__del__ of numerai_dataset.zip: 154MB [00:23, 12.2MB/s]> ignored

**Comment by kwgoodman** [comment]
Looks like it is coming from the progress bar (tqdm) which is called by numerapi. If you have tqdm installed then you might want to ask over at numerapi.
